.TH "NWCHEM" "1" "2012/06/11" "nwchem" "User Commands"

.SH "NAME"
nwchem \- high-performance computational chemistry software

.SH "SYNOPSIS"
.B nwchem
.I input_file

.SH "DESCRIPTION"
.B nwchem
provides many methods for computing the properties of molecular and periodic
systems using standard quantum mechanical descriptions of the electronic
wavefunction or density. Its classical molecular dynamics capabilities
provide for the simulation of macromolecules and solutions, including the
computation of free energies using a variety of force fields. These approaches
may be combined to perform mixed quantum-mechanics and molecular-mechanics
simulations.

.SH "OPTIONS"
There are no command line options to use.

.SH "SEE ALSO"
There is a comprehensive online manual at
\fI\%http://www.nwchem-sw.org/index.php/NWChem_Documentation\fP.

.SH "AUTHORS"
This manual page was written by
\fBDaniel Leidert\fP <\&daniel\.leidert@wgdd\.de\&> for the Debian GNU/Linux
distribution but may be used by others as well.
