name: docker_debian_packaging

on:
  release:
  schedule:
    - cron: '0 2 * * *'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  build:
 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 5
      - name: Setup cache
        id: setup-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/cache
          key: nwchem-debian-v001
      - name: delete artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: nwchemdockerpkg
          failOnError: false 
      - name: docker build
        run: |
          cd nwchem
          ./docker_build.sh
      - name: copy packages
        run: |
          find . -name "*deb" ||  true
          mkdir  -p nwchem-ubuntu.pkg
          cp `find nwchem -name "*deb" ` nwchem-ubuntu.pkg/.
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nwchemdockerpkg
          path: nwchem-ubuntu.pkg
          retention-days: 7
